### PR TITLE
Reposition visible toolbar when it is in a not visible stack of rotator.

### PR DESCRIPTION
**Pull request by jodator**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: Reposition visible toolbar when it is in a not visible stack of rotator. Closes ckeditor/ckeditor5#1957.

---

### Additional information

* The previous fix was causing problems in some edge cases - ie when toolbar was removed on focus lost and the whole logic was re-applied twice instead of just repositioning the toolbar. See https://github.com/ckeditor/ckeditor5/issues/1957.

### CODE REVIEW

**Comment by jodator** [comment]
@Mgsy Could you test this solution? I think that this fixes the toolbar on table with image bug but it could re-introduce: https://github.com/ckeditor/ckeditor5-widget/issues/92.

cc @pjasiun & @oskarwrobel  - I'm pinging you also with this as you better knew what happened in https://github.com/ckeditor/ckeditor5-widget/issues/92.

**Comment by jodator** [comment]
I didn't add any new tests as I feel that this fix looks like a better way of fixing the previous one.

Please do not merge until we decide if we're adding a test or not (I'll try to come up with a test-case anyway).

**Comment by jodator** [comment]
As for now I'm not able to reproduce the bug with automated test. I'll try tomorrow probably.

**Comment by Reinmar** [comment]
Heh, I know that we know this, but this API needs to be seriously rethought...

When a setter doesn't do anything, you know that it's bad.

image

**Pull request merged**
